### ISSUE TITLE
LogGMM does unnecessary type check of sample_size

### ISSUE THREAD

**Issue by ghost** [IQVIA-ML/TreeParzen.jl#19]
**Is your feature request related to a problem? Please describe.**

This is unnecessary given that the function signature insists upon `sample_size::Int`

https://github.com/IQVIA-ML/TreeParzen.jl/blob/532212cdf8b237d5214407e7c34569a60398b7b5/src/LogGMM.jl#L59-61

https://github.com/IQVIA-ML/TreeParzen.jl/blob/532212cdf8b237d5214407e7c34569a60398b7b5/src/LogGMM.jl#L94-96

**Comment by kainkad** [comment]
resolved by #42
