### ISSUE TITLE
Sampling strings?

### ISSUE THREAD

**Issue by yalwan-iqvia** [IQVIA-ML/TreeParzen.jl#32]
**Is your feature request related to a problem? Please describe.**
```
julia> example_space = Dict(
           :example => HP.PChoice(
               :example,
               [
                   Prob(0.1, "0"),
                   Prob(0.2, "1"),
                   Prob(0.7, "2"),
               ]
           )
       )
Dict{Symbol,TreeParzen.HP.PChoice} with 1 entry:
  :example => PChoice(Param(:example, CategoricalIndex([0.1, 0.2, 0.7])), ["0", "1", "2"])

julia> ask(example_space)
ERROR: MethodError: no method matching node(::String, ::Dict{Symbol,Real})

```

**Describe the solution you'd like**
I'd like to be able to sample from a set of strings

**Describe alternatives you've considered**
I note we can sample from symbols, but this would require user to make some additional plumbing before feeding samples to objective, which is a bad experience. In theory, sampling strings should be similarly possible

**Comment by iqml** [comment]
I think this is your culprit
https://github.com/IQVIA-ML/TreeParzen.jl/blob/a6f95d24d612141536d9cf47993f69c87d9eafd3/src/Resolve/nodes.jl#L386
