### ISSUE TITLE
Enable CompatHelper

### ISSUE THREAD

**Issue by ablaom** [IQVIA-ML/TreeParzen.jl#76]
It would be great if a maintainer could please enable compathelper: 

https://github.com/IQVIA-ML/TreeParzen.jl/actions/workflows/CompatHelper.yml

When a repo is dormant a while, this toggles off and needs to be re-enabled.

There are a couple of package compat updates needed downstream at MLJTuning.jl and CompatHelper will generate the necessary PRs.

**Comment by ablaom** [comment]
@kd-iqvia

**Comment by Kainka** [comment]
Hi @ablaom the CompatHelper is enabled for this repo. I can see the PR for MLJTuning.jl opened. Let us revise and merge it.
