### ISSUE TITLE
Please compare the speed and quality of results of pure julia packages (evotrees example) 

### ISSUE THREAD

**Issue by MrBenzWorld** [IQVIA-ML/TreeParzen.jl#83]
MLJ is best, i have started learning julia beacuse of MLJ. it is good ,and i appriciate it.
I would like to use pure julia pakages ( grading boosting packages , Ex: Evotrees)

Please , use some real dataset ( Ex : which are avaible Kaggle, House pricing .etc..)
Please use EvoTrees with MLJ , optmize it (TreeParzen is not working ). show the speed and quality of results.
I would like to use pure julia codes for my research work. But im not getting better results.
Please add some example with pure julia packages (MLJ+EvoTrees+TreeParzen ..etc) and compare results quality. you have lot examples but did not comapare.

Please help,
Thank you

**Comment by ablaom** [comment]
> (TreeParzen is not working ). 

Can you please explain why you say TreeParzen is not working? A simple example would be great. Please report results of `using Pkg; Pkg.status()`.

**Comment by ablaom** [comment]
https://github.com/IQVIA-ML/TreeParzen.jl/issues/84

**Comment by MrBenzWorld** [comment]
Thank you. Now it is working. @ablaom
