### ISSUE TITLE
Please tag a new release

### ISSUE THREAD

**Issue by ablaom** [IQVIA-ML/TreeParzen.jl#84]
Users are having trouble using the latest version of TreeParzen. One problem is that [this 6 month old commit](https://github.com/IQVIA-ML/TreeParzen.jl/commit/bf9032f584e00d29dba80a4f650c2c56476960e2) is still not live. 

@yaxxie @FatemehTahavori

**Comment by FatemehTahavori** [comment]
I can release @yaxxie if you are busy, let me know

**Comment by yaxxie** [comment]
Please go ahead if you can or else I can get to this tomorrow

**Comment by yaxxie** [comment]
https://github.com/JuliaRegistries/General/pull/72732

Thanks @FatemehTahavori

**Comment by MrBenzWorld** [comment]
Thank you for your propmt response. now is is working.  @ablaom
